// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuwmS2XAdqw2IQD30ltzIquADBV7AFpDo',
    appId: '1:585028919139:web:ec2d776378ad9bf7d87d56',
    messagingSenderId: '585028919139',
    projectId: 'moneycrafter-kaizen',
    authDomain: 'moneycrafter-kaizen.firebaseapp.com',
    databaseURL: 'https://moneycrafter-kaizen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneycrafter-kaizen.appspot.com',
    measurementId: 'G-85BXES0FR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEFUW2GZKi7dEeIguSkGS5DC3CmeZk3t0',
    appId: '1:585028919139:android:c4173674e84aa5f7d87d56',
    messagingSenderId: '585028919139',
    projectId: 'moneycrafter-kaizen',
    databaseURL: 'https://moneycrafter-kaizen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneycrafter-kaizen.appspot.com',
  );
}
